# Acoustic Evenness [AEI]

> [@Doohan2019] - The **Acoustic Evenness [AEI]** index describes the number and evenness of bins within a frequency range using the Gini coefficient [Villanueva-Rivera2011] and thus describes the balance of sound in the soundscape. It is based on the premise that natural landscapes are likely to produce more even soundscapes as animals vocalise across a wide range of frequencies; while altered landscapes are expected to have reduced evenness as the soundscape is dominated by technophony and geophony in fewer frequency bands [Fig. 1A; Villanueva-Rivera2011]; Evidence suggests that AEI may be a reliable proxy for biodiversity, after being tested in subtropical forests in eastern Australia [Fuller2015] and a variety of habitats [including crop lands] in the United States of America [Villanueva-Rivera2011].
>
> [@Jorge2018] - In the present study, there were moderate correlation between the number of bird species and the acoustic evenness index [AEI]. This relationship was stronger in the absence of the researcher field. During the bird dawn chorus, several bird [vocalizations][] fulfilled different frequency bins in different frequency bands on the [spectrogram][], which characterized the low acoustic regularity as observed at the studied site, corroborating [Fuller's[2015]][] results. It should be emphasized that, unlike the other analyzed indexes, a lower AEI indicates better conservation conditions in an environment [[Fuller2015][]].
>
> \@[@Eldridge2018] - The Acoustic Evenness and Acoustic Diversity Indices [AEI, ADI] are motivated by a similar analogy between species distribution and distribution of sound energy. Both are calculated by first dividing the spectrogram into N bins across a given range [typically 0-10 kHz] and taking the proportion of signal in each bin above a set threshold. ADI is the result of the Shannon Entropy [Jost, 2006] applied to the resultant vector; AEI is the Gini coefficient [Gini, 1971], providing a measure of evenness. These were originally developed to assess habitats along a gradient of degradation under the assumption that ADI and AEI would be respectively positively and negatively associated with habitat status as the distribution of sounds became more even with increasing diversity [Villanueva-Rivera2011]: ADI was shown to increase from agricultural to forested sites; AEI was shown to decrease over the same gradient, as expected. Negative, if weak, associations between AEI and biocondition [Eyre2015] have subsequently been corroborated [Fuller2015] and a significant positive association between ADI and avian species richness has been reported in the savannas of central Brazil [Alquezar and Machado, 2015].
>
> \@[@Eldridge2018] - The Acoustic Evenness Index [AEI] showed the highest correlation with species richness in the UK and contributed strongly to prediction in the multivariate regression model. The observed strong *positive* correlations between species richness and Acoustic Evenness Index and *negative* correlations between species richness and the entropy indices show that evenness of the spectra *decrease* with increasing richness for ADI, Ht and Hf. These finding are at odds with some previous short term correlation studies, but show the same patterns observed in longer term soundscape investigations [[Gage and Farina, 2017][]] and shed light on inconsistencies previously reported for entropy indices [[@Depraetere2012][], [Sueur2014][]]. Given that the measurement of acoustic diversity is foundational to RAS, reconciling these inconsistencies is important, as conflicting accounts exist both empirically and hypothetically.
You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
